! ispa/etc/frr/frr.conf
hostname ISPA
password zebra
enable password zebra
!
interface eth0
 ip ospf area 0
!
interface eth1
 ip ospf area 0
!
router ospf
 ! Advertise connected networks (Loopbacks)
 redistribute connected
 ! Default Information Originate (Source 78)
 default-information originate
 ! Passive Interface to R1 (Source 78)
 passive-interface eth0
!
! Static route distribution (if needed)
! redistribute kernel
!
log file /var/log/frr/frr.log