# R1 Interfaces
r1[0]="A"  # Maps to Serial5/0 (12.0.0.0/8)
r1[1]="B"  # Maps to Serial5/1 (111.0.0.0/8)
r1[2]="C"  # Maps to Serial5/2 (31.0.0.0/8)
r1[3]="D"  # Maps to FastEthernet0/0 (10.0.0.0/8)
r1[4]="E"  # Maps to FastEthernet2/0 (20.0.0.0/8)
r1[5]="F"  # Maps to FastEthernet3/0 (30.0.0.0/8)
pc0[0]='E'
# Enable FRR image
r1[image]="kathara/frr"

# R2 Interfaces
r2[0]="A"  # Maps to Serial5/0 (1.0.0.0/8)
r2[1]="H"  # Maps to Serial5/1 (23.0.0.0/8)
r2[2]="I"  # Maps to Serial5/2 (21.0.0.0/8)

# Enable FRR image
r2[image]="kathara/frr"

r3[0]="J"  # Maps to Serial5/0 (39.0.0.0/8)
r3[1]="H"  # Maps to Serial5/1 (23.0.0.0/8)
r3[2]="C"  # Maps to Serial5/2 (31.0.0.0/8)
r3[3]="M"  # Maps to Serial5/3 (34.0.0.0/8)
r3[4]="N"  # Maps to FastEthernet0/0 (30.0.0.0/8)
r3[5]="O"  # Maps to FastEthernet2/0 (32.0.0.0/8)
r3[6]="P"  # Maps to FastEthernet3/0 (33.0.0.0/8)

# Enable FRR image
r3[image]="kathara/frr"

r4[0]="M"  # Maps to Serial5/3 (34.0.0.0/8) [cite: 11]
r4[1]="R"  # Maps to Serial6/0 (45.0.0.0/8) [cite: 11]
r4[2]="S"  # Maps to Serial6/1 (46.0.0.0/8) [cite: 12]
r4[3]="T"  # Maps to FastEthernet0/0 (40.0.0.0/8) [cite: 14]

# Enable FRR image
r4[image]="kathara/frr"

# R5 Interfaces
r5[0]="R"  # Maps to Serial6/0 (45.0.0.0/8) [cite: 16]
r5[1]="V"  # Maps to Serial6/2 (56.0.0.0/8) [cite: 16]
r5[2]="W"  # Maps to Serial6/3 (58.0.0.0/8) [cite: 17]
r5[3]="X"  # Maps to FastEthernet0/0 (50.0.0.0/8) [cite: 17]

# Enable FRR image
r5[image]="kathara/frr"

# R6 Interfaces
r6[0]="S"  # Maps to Serial6/1 (46.0.0.0/8) - Connects to R4
r6[1]="V"  # Maps to Serial6/2 (56.0.0.0/8) - Connects to R5
r6[2]="Y"  # Maps to Serial6/3 (67.0.0.0/8)
r6[3]="Z"  # Maps to FastEthernet0/0 (60.0.0.0/8)

# Enable FRR image
r6[image]="kathara/frr"

# R7 Interfaces
r7[0]="Y"  # Maps to Serial6/3 (67.0.0.0/8) - Connects to R6
r7[1]="AA" # Maps to FastEthernet0/0 (70.0.0.0/8)

# Enable FRR image
r7[image]="kathara/frr"

# R8 Interfaces
r8[0]="W"   # Maps to Serial6/3 (58.0.0.0/8) - Connects to R5
r8[1]="BB"  # Maps to FastEthernet0/0 (80.0.0.0/8)

# Enable FRR image
r8[image]="kathara/frr"

# R9 Interfaces
r9[0]="J"   # Maps to Serial5/0 (39.0.0.0/8) - Connects to R3 [cite: 34]
r9[1]="CC"  # Maps to FastEthernet0/0 (90.0.0.0/8) [cite: 34]

# Enable FRR image
r9[image]="kathara/frr"

# R10 Interfaces
r10[0]="I"   # Maps to Serial5/2 (21.0.0.0/8) - Connects to R2 [cite: 38]
r10[1]="DD"  # Maps to FastEthernet0/0 (100.0.0.0/8) [cite: 38]

# Enable FRR image
r10[image]="kathara/frr"

# R11 Interfaces
# R11 Interfaces
r11[0]="EE"  # EIGRP 100
r11[1]="B"   # OSPF Area 3
r11[2]="FF"  # EIGRP 300

# Replace FRR with VyOS
r11[image]="kathara/frr"

# R12 Interfaces
r12[0]="EE"  # Maps to Serial5/0 (112.0.0.0/8) - Connects to R11
r12[1]="GG"  # Maps to FastEthernet0/0 (120.0.0.0/8)
pc12[0]="GG"
# Enable FRR image
r12[image]="kathara/frr"

# R13 Interfaces
r13[0]="FF"  # Maps to Serial5/2 (103.0.0.0/8) - Connects to R11

# Enable FRR image
r13[image]="kathara/frr"