! ispb/etc/frr/frr.conf
hostname ISPB
password zebra
enable password zebra
!
interface eth0
 ip ospf area 0
!
interface eth1
 ip ospf area 0
!
router ospf
 ! Advertise connected networks (Loopback3)
 redistribute connected
 ! Default Information Originate [Source 93]
 default-information originate
 ! Passive Interface to R1 [Source 93]
 passive-interface eth0
!
log file /var/log/frr/frr.log