vrrp_instance VI_10 {
    state MASTER
    interface br0.10
    virtual_router_id 10
    priority 105
    advert_int 4
    virtual_ipaddress {
        10.1.0.1
    }
}

vrrp_instance VI_20 {
    state BACKUP
    interface br0.20
    virtual_router_id 20
    priority 1
    advert_int 4
    virtual_ipaddress {
        10.2.0.1
    }
}

vrrp_instance VI_40 {
    state BACKUP
    interface br0.40
    virtual_router_id 40
    priority 1
    advert_int 4
    virtual_ipaddress {
        10.6.0.1
    }
}

vrrp_instance VI_99 {
    state MASTER
    interface br0.99
    virtual_router_id 99
    priority 105
    advert_int 4
    virtual_ipaddress {
        10.0.0.1
    }
}
