! csw1/etc/frr/frr.conf
hostname CSW1
password zebra
enable password zebra
!
interface lo
 ip address 10.0.0.77/32
!
router ospf
 ospf router-id 10.0.0.77
 passive-interface lo
 ! Networks (Area 0)
 network 10.0.0.32/30 area 0
 network 10.0.0.40/30 area 0
 network 10.0.0.44/30 area 0
 network 10.0.0.48/30 area 0
 network 10.0.0.52/30 area 0
 network 10.0.0.56/30 area 0
 network 10.0.0.77/32 area 0
!
log file /var/log/frr/frr.log