hostname R10
password zebra
enable password zebra

router ospf
 # Interface to R2
 network 21.0.0.0/8 area 4
 # Network to Stub Area
 network 100.0.0.0/8 area 4
 
 # Loopback advertisement
 network 110.0.0.0/8 area 4
 
 # Area 4 Stub (Must match R2's config)
 area 4 stub
!
log file /var/log/frr/frr.log