hostname R3
password zebra
enable password zebra
! Configure Interfaces First
interface eth4
 ip ospf passive
!
interface eth5
 ip ospf passive
!
interface eth6
 ip ospf passive
!
router ospf
 # Network statements
 network 23.0.0.0/8 area 0
 network 31.0.0.0/8 area 0
 network 34.0.0.0/8 area 0
 network 39.0.0.0/8 area 0
 network 30.0.0.0/8 area 0
 network 32.0.0.0/8 area 0
 network 33.0.0.0/8 area 0



!
log file /var/log/frr/frr.log