vrrp_instance VI_10 {
    state BACKUP
    interface br0.10
    virtual_router_id 10
    priority 1
    advert_int 1
    virtual_ipaddress {
        10.3.0.1
    }
}

vrrp_instance VI_20 {
    state MASTER
    interface br0.20
    virtual_router_id 20
    priority 105
    advert_int 1
    virtual_ipaddress {
        10.4.0.1
    }
}

vrrp_instance VI_30 {
    state MASTER
    interface br0.30
    virtual_router_id 30
    priority 105
    advert_int 1
    virtual_ipaddress {
        10.5.0.1
    }
}

vrrp_instance VI_99 {
    state BACKUP
    interface br0.99
    virtual_router_id 99
    priority 1
    advert_int 1
    virtual_ipaddress {
        10.0.0.17
    }
}
