! csw2/etc/frr/frr.conf
hostname CSW2
password zebra
enable password zebra
!
interface lo
 ip address 10.0.0.78/32
!
router ospf
 ospf router-id 10.0.0.78
 passive-interface lo
 ! Networks (Area 0)
 network 10.0.0.40/30 area 0
 network 10.0.0.36/30 area 0
 network 10.0.0.60/30 area 0
 network 10.0.0.64/30 area 0
 network 10.0.0.68/30 area 0
 network 10.0.0.72/30 area 0
 network 10.0.0.78/32 area 0
!
log file /var/log/frr/frr.log