! dswb2/etc/frr/frr.conf
hostname DSW-B2
password zebra
enable password zebra
!
interface lo
 ip address 10.0.0.82/32
!
interface eth5
 ip ospf area 0
!
interface eth6
 ip ospf area 0
!
interface br0.10
 ip ospf area 0
!
interface br0.20
 ip ospf area 0
!
interface br0.30
 ip ospf area 0
!
interface br0.99
 ip ospf area 0
!
router ospf
 ospf router-id 10.0.0.82
 log-adjacency-changes
 passive-interface lo
 passive-interface br0.10
 passive-interface br0.20
 passive-interface br0.30
!
log file /var/log/frr/frr.log
