hostname R6
password zebra
enable password zebra

router ospf
 # Network statements
 network 60.0.0.0/8 area 1
 network 56.0.0.0/8 area 1
 network 67.0.0.0/8 area 1
 network 46.0.0.0/8 area 1

 # Loopback networks (summarized to /8)
 network 16.0.0.0/8 area 1

!
log file /var/log/frr/frr.log