hostname R1
password zebra
enable password zebra

! Configure Interfaces First
interface eth3
 ip ospf passive
!
interface eth4
 ip ospf passive
!
interface eth5
 ip ospf passive
!

! Configure OSPF Process
router ospf
 network 12.0.0.0/8 area 0
 network 31.0.0.0/8 area 0
 network 111.0.0.0/8 area 3
 network 10.0.0.0/8 area 0
 network 20.0.0.0/8 area 0
 network 30.0.0.0/8 area 0
!
log file /var/log/frr/frr.log