! aswa3/etc/frr/frr.conf
hostname ASW-A3
password zebra
enable password zebra
!
interface br0.99
 description Management VLAN
 ip address 10.0.0.6/28
!
ip route 0.0.0.0/0 10.0.0.1
!
log file /var/log/frr/frr.log