! aswb3/etc/frr/frr.conf
hostname ASW-B3
password zebra
enable password zebra
!
interface br0.99
 description Management VLAN
 ip address 10.0.0.22/28
!
ip route 0.0.0.0/0 10.0.0.17
!
log file /var/log/frr/frr.log