! r1/etc/frr/frr.conf
hostname R1
password zebra
enable password zebra
!
interface lo
 ip address 10.0.0.76/32
!
router ospf
 ospf router-id 10.0.0.76
 passive-interface lo
 ! Advertise internal links to Core
 network 10.0.0.32/30 area 0
 network 10.0.0.36/30 area 0
 network 10.0.0.76/32 area 0
 ! Advertise Default Route to Core [Source 112]
 default-information originate
!
log file /var/log/frr/frr.log