hostname R2
password zebra
enable password zebra

router ospf
 # Network statements
 network 1.0.0.0/8 area 0
 network 23.0.0.0/8 area 0
 network 21.0.0.0/8 area 4

 # Stub Area Configuration
 area 4 stub

!
log file /var/log/frr/frr.log